### PR TITLE
fix(update/4): improve Mongo.update/4 function

### LINKED ISSUE #243: Endless recursion with wrong arguments for Mongo.update/4
Hi,

I think I stumbled upon a bug: if someone supplies wrong arguments to Mongo.update/4, it results in an endless recursive call to normalise_updates/1 (a private function). The update/4 has 4 params: topology_pid, collection, updates, opts . `updates` should be a list of keyword lists, but if it's anything else is supplied (e.g empty list) it seems to goes south.

This is the snippet which I think are relevant (from https://github.com/zookzook/elixir-mongodb-driver/blob/master/lib/mongo.ex#L1133 ):

```elixir
  def update(topology_pid, coll, updates, opts) do
    write_concern =
      filter_nils(%{
        w: Keyword.get(opts, :w),
        j: Keyword.get(opts, :j),
        wtimeout: Keyword.get(opts, :wtimeout)
      })

    normalised_updates = updates |> normalise_updates()
    # rest of update function
    
  defp normalise_updates([[{_, _} | _] | _] = updates) do
    updates
    |> Enum.map(&normalise_update/1)
  end

  defp normalise_updates(updates), do: normalise_updates([updates])
```

If you agree this is a bug, I'm willing to submit a patch. 

I'm a bit new to Mongo, so not sure what the expected behaviour is, but I propose to change it such that update/4 checks if `updates` is a keyword list with at least q/query + u/update/update keys, WDYT?

Small snippet to reproduce:

```elixir
{:ok, conn} = Mongo.start_link(url: "mongodb://localhost:27017/example")
Mongo.update(conn, "example", :rick_roll, [])
```

### PR DESCRIPTION
**Pull request by Tuxified**
Changes:

- prevent endless recursion when supplied empty list
- make options list optional
- add more documentation + tests

Fixes #243

### CODE REVIEW

File: lib/mongo.ex [hunk 1]
```diff
@@ -1170,11 +1192,12 @@ defmodule Mongo do
...
   defp normalise_updates([[{_, _} | _] | _] = updates) do
-    updates
-    |> Enum.map(&normalise_update/1)
+    Enum.map(updates, &normalise_update/1)
   end
 
-  defp normalise_updates(updates), do: normalise_updates([updates])
+  defp normalise_updates([{_, _} | _] = updates), do: normalise_updates([updates])
+
+  defp normalise_updates(updates), do: updates
```
Comment (Tuxified) [inline lib/mongo.ex:1200]: Only normalise Keyword lists, letting Mongo return an error if the updates are not in an expected format

File: lib/mongo.ex [hunk 2]
```diff
@@ -1129,7 +1129,29 @@ defmodule Mongo do
 
   e.g. long-hand `query` becomes short-hand `q`, snake case `array_filters`
   becomes `arrayFilters`
+
```
Comment (Tuxified) [inline lib/mongo.ex:1132]: Should we make a mention of some of the usual options (upsert & multi) ? I was a bit surprised they couldn't be combined, but it makes sense after some thought.

File: lib/mongo.ex [hunk 3]
```diff
@@ -1129,7 +1129,29 @@ defmodule Mongo do
...
+        Mongo.update(MongoPool,
+          "test_collection",
+          query: %{foo: 4},
+          update: %{foo: 5, new_field: "new_value"}},
+          upsert: true)
+
+        Mongo.update(MongoPool, "test_collection", [
+          [q: %{foo: 24}, update: %{flag: "old"}],
+          [q: %{foo: 99}, update: %{luftballons: "yes"}, upsert: true]
+        ])
```
Comment (Tuxified) [inline lib/mongo.ex:1150]: Do these examples suffice? I think this shows the most common ways of supplying updates, WDYT?

File: lib/mongo.ex (hunk 1 above)
Comment (zookzook) [reply lib/mongo.ex:1200]: Can you add some names for the placeholders to increase the readability? For example:

Instead of 
```
defp normalise_updates([[{_, _} | _] | _] = updates) do
```

it would be nice to have
```
## maps lists of keywords list
defp normalise_updates([[{_key, _value} | _rest] | _updates] = updates) do
```

**Review by zookzook — APPROVED** [review]
Looks good to me :-) Maybe you want to add some comments to the private functions

**Review by zookzook — APPROVED** [review]
Thank you!

**Comment by Tuxified** [comment]
Thanks for the review, I added variable names and comments for readability. I don't have write access, so can you merge it when you have time.
